                  ALGORITHÍ COMPUTERÓ    Introductioî tï Java
                  ------------------­    Topiã ­ 1

Â leä tï C¬ Ã evoleä intï C++¬ anä C+« seô thå stagå foò Java.

Althougè  Javá  haó  becomå inseparablù linkeä  witè  thå  onlinå 
environmenô  oæ  thå internet¬ iô ió importanô tï  remembeò  thaô 
Javá  ió  firsô  anä foremosô á  programminç  language®  Computeò 
languagå  innovatioî anä developmenô occuró foò  twï  fundamentaì 
reasons:

ª Tï adapô tï changinç environmentó anä uses.
ª Tï implemenô refinementó anä improvementó iî thå arô oæ
  programming.

Thå creatioî oæ Javá waó driveî bù botè elementó iî nearlù  equaì 
measure.

1İ Java'ó Lineage:
------------------
     Javá  ió relateä tï C++¬ whicè ió á direcô descendanô oæ  C® 
Mucè  oæ  thå  characteò  oæ Javá ió  inheriteä  froí  theså  twï 
languages®  Froí  C¬  Javá deriveó itó  syntax®  Manù  oæ  Java'ó 
objecô-orienteä featureó werå influenceä bù C++® Iî fact¬ severaì 
oæ  Java'ó defininç characteristicó comå froí ­ oò arå  responseó 
tï ­ itó predecessors.

1.aİ Thå Birtè oæ Moderî Programmingº C
-------------------------------------
     Thå Ã languagå shooë thå wholå world® Itó impacô shoulä  noô 
bå  underestimated¬  becauså  iô fundamentallù  changeä  thå  waù 
programminç  waó approacheä anä thoughô about® Thå creatioî oæ  Ã 
waó  á  direcô resulô oæ thå neeä foò  á  structured¬  efficient¬ 
higè-leveì  languagå  thaô  coulä  replacå  assemblù  codå   wheî 
creatinç systemó programs® Wheî á computeò languagå ió  designed¬ 
trade-offó arå ofteî made® Foò example:

ª Easå oæ uså versuó power.
ª Safetù versuó efficiency.
ª Rigiditù versuó extensibility.

1.bİ Thå Neeä foò C++:
--------------------
     Thå increaseä complexitù iî programminç leä tï thå inventioî 
oæ  C++® Eveî thå structureä programminç methods¬ oncå á  projecô 
reacheó á certaiî size¬ itó complexitù exceedó whaô á  programmeò 
caî  manage® Bù thå earlù 1980s¬ manù projectó werå  pushinç  thå 
structureä approacè pasô itó limits® Tï solvå thió problem¬ á ne÷ 
waù  tï  prograí  waó invented® Thió  methoä  ió  calleä  objecô-
orienteä programminç (OOP)® OOĞ ió á programminç methodologù thaô 
helpó organizå compleø programó througè thå uså oæ  inheritance¬ 
encapsulatioî¬ anä polymorphism.
.paŠ1.cİ Thå stagå ió Seô foò Java:
-----------------------------
     Bù thå enä oæ thå 1980ó anä thå earlù 1990s¬ objecô-orienteä 
programminç  usinç  C+« tooë hold® Becauså C+« blendeä  thå  higè 
efficiencù  anä stylistiã elementó oæ Ã witè thå  objecô-orienteä 
paradigm¬  iô waó á languagå thaô coulä bå useä tï creatå á  widå 
rangå  oæ  programs®  However¬ jusô aó iî thå  past¬  therå  werå 
forceó  brewinç thaô would¬ oncå again¬ drivå  computeò  languagå 
evolutioî forward.

2İ Thå Creatioî oæ Java:
------------------------
     Thå originaì impetuó foò Javá waó noô thå Internet® Instead¬ 
thå  primarù motivatioî waó thå neeä foò  á  platforí-independenô 
(thaô  is¬ architecturå-neutral© languagå thaô coulä bå  useä  tï 
creatå  softwarå  tï bå embeddeä iî variouó  consumeò  electroniã 
devices¬ sucè aó microwavå ovenó anä remotå controls® Aó yoõ  caî 
probablù  guess¬ therå arå manù differenô typeó oæ CPUó  useä  aó 
controllers®  Thå  troublå  witè  Ã  anä  C+«  (anä  mosô   otheò 
languages©  ió  thaô  theù  arå designeä tï  bå  compileä  foò  á 
specifiã  target® Whilå iô ió possiblå tï compilå á  C+«  prograí 
foò  jusô  abouô anù typå oæ CPU¬ tï dï sï requireó  á  fulì  C+« 
compileò targeteä foò thaô CPU® Thå probleí ió thaô compileró arå 
expensivå anä timå-consuminç tï create® Aî easieò ­ anä morå cosô 
efficienô  ­  solutioî waó needed® Iî aî attempô tï finä  sucè  á 
solution¬ Goslinç anä otheró begaî worë oî á portable¬  platforí-
neutraì  languagå thaô coulä bå useä tï producå codå  thaô  woulä 
ruî  oî  á  varietù oæ CPUó undeò  differenô  environments®  Thió 
efforô ultimatelù leä tï thå creatioî oæ Java.
     Abouô  thå timå thaô thå detailó oæ Javá werå  beinç  workeä 
out¬ á second¬ anä ultimatelù morå important¬ factoò waó emerginç 
thaô woulä plaù á cruciaì rolå iî thå futurå oæ Java® Thió seconä 
forcå  was¬ oæ cource¬ thå Worlä Widå Web® Haä thå Weâ noô  takeî 
shapå  aô  abouô thå samå timå thaô Javá waó  beinç  implemented¬ 
Javá  mighô  havå  remaineä á usefuì  buô  obscurå  languagå  foò 
programminç consumeò electronics® However¬ witè thå emergencå  oæ 
Worlä  Widå Web¬ Javá waó propelleä tï thå forefronô oæ  computeò 
languagå   design¬  becauså  thå  Web¬  too¬  demandeä   portablå 
programs.
     Javá  waó designeä tï solvå á certaiî seô oæ  problems®  C+« 
waó designeä tï solvå á differenô seô oæ problems® Botè wilì  cï-
exisô foò manù yearó tï come.
     Javá  ió  tï  Interneô programminç whaô  Ã  waó  tï  systemó 
programmingº á revolutionarù forcå thaô wilì changå thå world.

[3İ Whù Javá ió importanô tï thå Internet:
------------------------------------------
     Javá  expandó  thå universå oæ objectó thaô caî  movå  abouô 
freelù iî cyberspace® Iî á networë therå arå twï typeó oæ objectó 
thaô  arå  transmitteä  betweeî  thå  serveò  anä  youò  personaì 
computerº passivå informatioî anä dynamic¬ activå programs.
.paŠ3.aİ Javá Appletó anä applications:
-----------------------------------
Aî  applicatioî ió thå prograí thaô runó oî youò computer¬  undeò 
thå  operatinç systeí oæ thaô computer® Thaô is¬  aî  applicatioî 
createä bù Javá ió morå oò lesó likå onå createä usinç Ã oò  C++® 
Aî  appleô ió aî applicatioî designeä tï bå transmitteä oveò  thå 
Interneô anä executeä bù á Javá-compatiblå Weâ browser® Aî appleô 
ió  actuallù á tinù Javá program¬ dynamicallù  downloadeä  acrosó 
thå network¬ jusô likå aî image¬ sounä file¬ oò videï clip.

[4İ Java'ó Magiã º Thå Bytecodes:
---------------------------------




[5İ Thå Javá Buzzwords:
-----------------------
5.aİ Simple




5.bİ Secure



5.cİ Portable



5.dİ Object-oriented



5.eİ Robust



5.fİ Multithreaded



5.gİ Architecture-neutral




5.hİ Interpreted





Š5.iİ Higè-performance





5.jİ Distributed





5.kİ Dynamic






[6İ Ió Javá aî Enhanceä HTML?






[7İ Whaô ió offereä iî Javá Courså aô Algorithí Computers?
(Refeò tï Syllabus)
